#User Configuration

#OE_TERMINAL = "tmux"

IMAGE_INSTALL:append = " gnuradio gnuradio-runtime gnuradio-blocks gnuradio-digital \
    gnuradio-analog gnuradio-fft gnuradio-filter gnuradio-fec gnuradio-pmt \
    gnuradio-gr gnuradio-audio gnuradio-zeromq"

RM_WORK_EXCLUDE += "gnuradio"