#User Configuration

#OE_TERMINAL = "tmux"

# Enable the Package Test framework globally
DISTRO_FEATURES:append = " ptest"

# Explicitly command BitBake to install the official test suites
IMAGE_INSTALL:append = " ptest-runner volk-ptest gnuradio-ptest cmake"

IMAGE_INSTALL:append = " gnuradio gnuradio-runtime gnuradio-blocks gnuradio-digital \
    gnuradio-analog gnuradio-fft gnuradio-filter gnuradio-fec gnuradio-pmt \
    gnuradio-gr gnuradio-audio gnuradio-zeromq python3-pyyaml"

RM_WORK_EXCLUDE += "gnuradio"