#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright 2026 CAAI.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
"""Spawns tests/shell_stub.py on a pty as its controlling terminal (via
os.forkpty() -- see fake_board.py's docstring for why this matters, in
particular for the orphan-recovery mode, which depends on a real SIGINT
being generated by Ctrl-C), the login-machine counterpart to fake_board.py's
real receiver subprocess.
"""

import os
import signal
import sys
import time

_HERE = os.path.dirname(os.path.abspath(__file__))
STUB_PATH = os.path.join(_HERE, "shell_stub.py")


class FakeShell:
    def __init__(self, mode, user="petalinux", password="1234", python=None):
        self.master_fd = None
        self._pid = None
        self._mode = mode
        self._user = user
        self._password = password
        self._python = python or sys.executable

    def start(self):
        pid, master_fd = os.forkpty()
        if pid == 0:
            cmd = [self._python, STUB_PATH, "--mode", self._mode,
                  "--user", self._user, "--password", self._password]
            try:
                os.execvp(cmd[0], cmd)
            finally:
                os._exit(127)
        self.master_fd = master_fd
        self._pid = pid
        return pid

    def transport(self, transcript=None):
        from ..core.transport import FdTransport
        return FdTransport(self.master_fd, transcript=transcript, name="fake-shell")

    def stop(self):
        if self._pid is not None:
            try:
                os.kill(self._pid, signal.SIGTERM)
            except ProcessLookupError:
                pass
            if self._waitpid_timeout(5.0) is None:
                try:
                    os.kill(self._pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
                self._waitpid_timeout(5.0)
        if self.master_fd is not None:
            try:
                os.close(self.master_fd)
            except OSError:
                pass

    def _waitpid_timeout(self, timeout):
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            try:
                done_pid, status = os.waitpid(self._pid, os.WNOHANG)
            except ChildProcessError:
                return None
            if done_pid == self._pid:
                return status
            time.sleep(0.05)
        return None

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        self.stop()
