#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright 2026 CAAI.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
"""core/generate.py: the Process phase end to end.

`grcc` is stubbed with a small script rather than mocked out, so the
subprocess boundary -- argv, exit status, the merged output stream, the
file actually appearing on disk -- is exercised for real. A real GNU Radio
install is not needed to test that we invoke it correctly and read its
result correctly, and requiring one would mean these never run in CI.
"""

import os
import shutil
import stat
import tempfile
import unittest

from . import grc_fixtures as fx
from ..core import generate, report
from ..core.generate import GenerateError
from ..core.grcfile import GrcError

# A stand-in for grcc. Writes <out>/<flowgraph id>.py, named from the `id:`
# option the way the real one does, and can be told to fail instead.
STUB = '''#!/usr/bin/env python3
import os, re, sys
argv = sys.argv[1:]
out = argv[argv.index("-o") + 1]
src = argv[-1]
print("stub grcc: %s -> %s" % (src, out))
if os.environ.get("STUB_FAIL"):
    print("stub grcc: deliberate failure", file=sys.stderr)
    sys.exit(3)
if os.environ.get("STUB_SILENT"):
    sys.exit(0)
text = open(src).read()
fg_id = re.search(r"^\\s*id: (\\S+)$", text, re.M).group(1)
if os.environ.get("STUB_ODD_NAME"):
    fg_id = "something_else"
with open(os.path.join(out, fg_id + ".py"), "w") as fh:
    fh.write("# generated by the stub\\nPYTHONPATH=%r\\nCWD=%r\\n"
             % (os.environ.get("PYTHONPATH", ""), os.getcwd()))
'''


@unittest.skipUnless(fx.HAVE_YAML, "PyYAML not installed")
class GenerateTestCase(unittest.TestCase):
    def setUp(self):
        self.dir = tempfile.mkdtemp(prefix="fau_generate_")
        self.addCleanup(shutil.rmtree, self.dir, ignore_errors=True)
        self.build = os.path.join(self.dir, "build")
        self.grcc = os.path.join(self.dir, "grcc_stub")
        with open(self.grcc, "w") as fh:
            fh.write(STUB)
        os.chmod(self.grcc, os.stat(self.grcc).st_mode | stat.S_IEXEC)
        # core/report.py writes through a process-global sink; swallow it
        # so the suite's output stays readable, and put it back after.
        prev = report.set_sink(lambda _t, _e: None)
        self.addCleanup(report.set_sink, prev)
        for key in ("STUB_FAIL", "STUB_SILENT", "STUB_ODD_NAME"):
            os.environ.pop(key, None)
            self.addCleanup(os.environ.pop, key, None)

    def _grc(self, document=None, name=None):
        return fx.write(document or fx.rx_with_gui(), self.dir, name)

    def _process(self, document=None, **kw):
        kw.setdefault("build_dir", self.build)
        kw.setdefault("grcc", self.grcc)
        return generate.process(self._grc(document), **kw)


class TestStamp(unittest.TestCase):
    def test_a_missing_file_stamps_as_none(self):
        self.assertIsNone(generate.stamp_of("/nonexistent/at/all"))


class TestBuildDir(unittest.TestCase):
    def test_same_name_in_two_projects_gets_two_directories(self):
        # Otherwise one project's generated .py overwrites the other's,
        # which is the deploy-the-wrong-file failure this tool exists for.
        a = generate.build_dir_for("/projects/alpha/tx.grc")
        b = generate.build_dir_for("/projects/beta/tx.grc")
        self.assertNotEqual(a, b)
        self.assertIn("tx-", os.path.basename(a))

    def test_it_is_stable_across_calls(self):
        self.assertEqual(generate.build_dir_for("/p/tx.grc"),
                         generate.build_dir_for("/p/tx.grc"))


class TestProcess(GenerateTestCase):
    def test_it_produces_a_py_a_headless_grc_and_a_target(self):
        gen = self._process()
        self.assertTrue(os.path.isfile(gen.py_path))
        self.assertTrue(os.path.isfile(gen.headless_grc))
        self.assertEqual(gen.target, "rx")
        self.assertEqual(os.path.basename(gen.py_path), "rx_demo.py")

    def test_the_headless_copy_is_beside_the_generated_py_for_diffing(self):
        gen = self._process()
        self.assertEqual(os.path.dirname(gen.headless_grc), self.build)
        self.assertTrue(gen.headless_grc.endswith(".headless.grc"))

    def test_source_dir_points_back_at_the_original(self):
        # Payload assembly needs it: the generated .py is in the build dir
        # but a sibling module it imports is still beside the .grc.
        gen = self._process()
        self.assertEqual(gen.source_dir, os.path.dirname(gen.grc_path))
        self.assertNotEqual(gen.source_dir, os.path.dirname(gen.py_path))

    def test_grcc_runs_with_the_source_dir_importable(self):
        # An `import` block is EVALUATED during code generation, so a
        # flowgraph with a helper module fails to compile at all unless
        # that module can be imported from where grcc runs. The stub
        # records the PYTHONPATH and cwd it was given.
        gen = self._process()
        with open(gen.py_path) as fh:
            generated = fh.read()
        self.assertIn(gen.source_dir, generated)

    def test_the_target_mismatch_gate_refuses(self):
        with self.assertRaises(GrcError) as cm:
            self._process(expect_target="tx")
        self.assertIn("wrong PL design", str(cm.exception))

    def test_a_matching_mode_passes(self):
        self.assertEqual(self._process(expect_target="rx").target, "rx")

    def test_a_non_role_mode_is_only_advisory(self):
        # bitstreams.json mode keys are free-form; "bootstrap" is not a
        # claim about TX or RX, so it must not refuse.
        self.assertEqual(self._process(expect_target="bootstrap").target, "rx")

    def test_dry_run_writes_the_headless_copy_but_no_python(self):
        gen = self._process(dry_run=True)
        self.assertIsNone(gen.py_path)
        self.assertTrue(os.path.isfile(gen.headless_grc))
        self.assertTrue(gen.is_stale())


class TestStaleness(GenerateTestCase):
    def test_a_fresh_result_is_not_stale(self):
        self.assertFalse(self._process().is_stale())

    def test_touching_the_grc_makes_it_stale(self):
        gen = self._process()
        st = os.stat(gen.grc_path)
        os.utime(gen.grc_path,
                 ns=(st.st_mtime_ns + 10_000_000, st.st_mtime_ns + 10_000_000))
        self.assertTrue(gen.is_stale())

    def test_deleting_the_generated_py_makes_it_stale(self):
        gen = self._process()
        os.unlink(gen.py_path)
        self.assertTrue(gen.is_stale())


class TestGrccFailures(GenerateTestCase):
    def test_a_missing_grcc_says_what_to_do_instead(self):
        with self.assertRaises(GenerateError) as cm:
            self._process(grcc="definitely-not-a-real-program")
        message = str(cm.exception)
        self.assertIn("not on PATH", message)
        self.assertIn(".py", message)

    def test_a_nonzero_exit_carries_grccs_own_output(self):
        os.environ["STUB_FAIL"] = "1"
        with self.assertRaises(GenerateError) as cm:
            self._process()
        message = str(cm.exception)
        self.assertIn("deliberate failure", message)
        self.assertIn("exit 3", message)

    def test_the_headless_copy_survives_a_failure_for_inspection(self):
        os.environ["STUB_FAIL"] = "1"
        with self.assertRaises(GenerateError):
            self._process()
        self.assertTrue(os.path.isfile(
            os.path.join(self.build, "rx_demo.headless.grc")))

    def test_success_with_no_output_file_is_still_a_failure(self):
        # grcc exiting 0 without writing anything would otherwise become a
        # deploy of whatever .py happened to be in the build dir already.
        os.environ["STUB_SILENT"] = "1"
        with self.assertRaises(GenerateError) as cm:
            self._process()
        self.assertIn("wrote no Python file", str(cm.exception))

    def test_an_unexpected_output_name_is_found_by_what_changed(self):
        # grcc names its output from the `id` option; if that ever stops
        # being true, falling back to "the one file it touched" beats
        # failing on a naming assumption.
        os.environ["STUB_ODD_NAME"] = "1"
        gen = self._process()
        self.assertEqual(os.path.basename(gen.py_path), "something_else.py")


class TestGates(GenerateTestCase):
    def test_a_flowgraph_with_no_fau_block_never_reaches_grcc(self):
        document = fx.doc([fx.block("v", "variable", {"value": "1"})])
        with self.assertRaises(GrcError):
            self._process(document)
        self.assertFalse(os.path.isdir(self.build))

    def test_message_controls_refuse_by_default_and_pass_with_consent(self):
        document = fx.doc([fx.fau_source(), fx.msg_button()])
        with self.assertRaises(GrcError):
            self._process(document)
        gen = self._process(document, allow_message_controls=True)
        self.assertTrue(os.path.isfile(gen.py_path))


class TestLooksLikeGrc(unittest.TestCase):
    def test_extension_matching_ignores_case_and_whitespace(self):
        self.assertTrue(generate.looks_like_grc("  a/b/tx.GRC  "))
        self.assertTrue(generate.looks_like_grc("tx.grc"))
        self.assertFalse(generate.looks_like_grc("tx.py"))
        self.assertFalse(generate.looks_like_grc("grc"))


if __name__ == "__main__":
    unittest.main()
